apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: iscsi-monitor
spec:
  selector:
    matchLabels:
      app: iscsi-monitor
  template:
    metadata:
      labels:
        app: iscsi-monitor
    spec:
      nodeSelector:
        storage-node: true
    spec:
      containers:
      - name: iscsi-monitor
        image: iscsi-monitor:latest
        imagePullPolicy: Never
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-dev
          mountPath: /dev
        - name: host-run
          mountPath: /run
        - name: host-proc
          mountPath: /hostproc
      volumes:
      - name: host-dev
        hostPath:
          path: /dev
      - name: host-run
        hostPath:
          path: /run
      - name: host-proc
        hostPath:
          path: /proc